name: Enhancement Request
description: "Enhance existent functionality or suggest a new feature"
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Describe the enhancement/feature
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: |
        Add mockups, screenshots etc.
      description: You can drag images into the text input below
    validations:
      required: false
