ergo {
  # Settings for node view holder regime. See papers.yellow.ModifiersProcessing.md
  node {
    # Is the node is doing mining
    mining = false
  }
}

scorex {
  network {
    bindAddress = "0.0.0.0:9001"
    agentName = "testnet-ergo-integration-test"
  }
  restApi {
    bindAddress = "0.0.0.0:9051"
    # Test-only credential used by NodeApi.
    apiKeyHash = "2688dbbdcefcbc8852b756efdd976905a21dcc0016dab48edca0f10f791fdcde"
  }
}
