# load metric data from CSV files generated by the node
# NOTE: run this script from root directory of the cloned ergo repository

DB_FILE=Metrics.sqlite
METRICS_DIR=mainnet/data/metrics

echo loading appendFullBlock

sqlite3 -separator ';' $DB_FILE \
   '.import '$METRICS_DIR'/appendFullBlock.csv appendFullBlock'

echo loading applyTransactions
sqlite3 -separator ';' $DB_FILE \
   '.import '$METRICS_DIR'/applyTransactions.csv applyTransactions'

echo loading createUtxoState
sqlite3 -separator ';' $DB_FILE \
   '.import '$METRICS_DIR'/createUtxoState.csv createUtxoState'

echo loading validateTxStateful
sqlite3 -separator ';' $DB_FILE \
   '.import '$METRICS_DIR'/validateTxStateful.csv validateTxStateful'

echo loading verifyScript
sqlite3 -separator ';' $DB_FILE \
   '.import '$METRICS_DIR'/verifyScript.csv verifyScript'
