# load metric data from CSV files generated by the node
# NOTE: run this script from root directory of the cloned ergo repository

DB_FILE=Metrics.sqlite
METRICS_DIR=mainnet/data/metrics

echo loading appendFullBlock4

sqlite3 -separator ';' $DB_FILE \
   '.import '$METRICS_DIR'/appendFullBlock.csv appendFullBlock4'

echo loading applyTransactions4
sqlite3 -separator ';' $DB_FILE \
   '.import '$METRICS_DIR'/applyTransactions.csv applyTransactions4'

echo loading createUtxoState4
sqlite3 -separator ';' $DB_FILE \
   '.import '$METRICS_DIR'/createUtxoState.csv createUtxoState4'

echo loading validateTxStateful4
sqlite3 -separator ';' $DB_FILE \
   '.import '$METRICS_DIR'/validateTxStateful.csv validateTxStateful4'

echo loading verifyScript4
sqlite3 -separator ';' $DB_FILE \
   '.import '$METRICS_DIR'/verifyScript.csv verifyScript4'
